"""Static sharing metadata shared by entry and general pages."""

from functools import lru_cache
import hashlib
from html import escape
from html.parser import HTMLParser
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
IMAGE_VERSION = "v1"
IMAGE_DIRECTORY = f"assets/og/{IMAGE_VERSION}"
HEADLINES_PATH = ROOT / "data/share_headlines.json"
WIDTH, HEIGHT = 1200, 630


def source_fingerprint(entry):
    source = {field: entry[field] for field in ("title", "verse_ref", "bible_verse", "poem")}
    serialized = json.dumps(source, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode()).hexdigest()


@lru_cache(maxsize=1)
def load_headlines():
    return json.loads(HEADLINES_PATH.read_text(encoding="utf-8"))


def validate_headlines(entries, headlines):
    expected = {entry["mmdd"] for entry in entries}
    if set(headlines) != expected:
        raise ValueError("Share headlines must cover exactly the source entry dates")
    for entry in entries:
        record = headlines[entry["mmdd"]]
        if record.get("source_title") != entry["title"] or record.get("source_sha256") != source_fingerprint(entry):
            raise ValueError(f"Review the share headline after source changes: {entry['mmdd']}")
        headline = record.get("headline", "")
        if not isinstance(headline, str) or not headline.strip() or headline != " ".join(headline.split()):
            raise ValueError(f"Invalid share headline: {entry['mmdd']}")


def image_filename(entry=None):
    if entry is None:
        return "site.png"
    month = entry["display_date"].split()[0].lower()
    return f"{month}-{entry['day']}.png"


def image_alt(entry=None):
    if entry is None:
        text = "Lincoln's Devotional; Daily readings"
    else:
        text = f"{load_headlines()[entry['mmdd']]['headline']}; {entry['display_date']}"
    return f"Lincoln in a stovepipe hat above {text}, in ivory lettering on a dark background."


def build_share_title(entry):
    return f"{entry['display_date']} — {entry['title']}"


def render_image_meta(site_url, entry=None, title=None, description=None):
    url = f"{site_url.rstrip('/')}/{IMAGE_DIRECTORY}/{image_filename(entry)}"
    alt = image_alt(entry)
    tags = [
        ("property", "og:locale", "en_US"),
        ("property", "og:image", url),
        ("property", "og:image:type", "image/png"),
        ("property", "og:image:width", str(WIDTH)),
        ("property", "og:image:height", str(HEIGHT)),
        ("property", "og:image:alt", alt),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:image", url),
        ("name", "twitter:image:alt", alt),
    ]
    if title is not None:
        tags.append(("name", "twitter:title", title))
    if description is not None:
        tags.append(("name", "twitter:description", description))
    return "\n    ".join(
        f'<meta {attribute}="{key}" content="{escape(value, quote=True)}" />'
        for attribute, key, value in tags
    )


class SocialHeadParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.meta = {}

    def handle_starttag(self, tag, attrs):
        attributes = dict(attrs)
        if tag == "meta":
            key = attributes.get("property", attributes.get("name"))
            self.meta[key] = attributes.get("content", "")


def refresh_static_share_meta(path, site_url):
    """Keep general-page cards aligned with their existing editorial metadata."""
    html = path.read_text(encoding="utf-8")
    head, tail = html.split("</head>", 1)
    parser = SocialHeadParser()
    parser.feed(head)
    block = "<!-- Sharing image metadata: generated by tools/generate_entry_pages.py -->\n    "
    block += render_image_meta(site_url, title=parser.meta["og:title"], description=parser.meta["og:description"])
    block += "\n    <!-- End sharing image metadata -->"
    pattern = r"<!-- Sharing image metadata:.*?<!-- End sharing image metadata -->"
    if re.search(pattern, head, re.S):
        head = re.sub(pattern, lambda _: block, head, flags=re.S)
    else:
        head = re.sub(r'    <meta name="twitter:[^"]+"[^>]*>\n', "", head)
        head = head.replace('    <link rel="icon"', f'    {block}\n    <link rel="icon"', 1)
    path.write_text(head + "</head>" + tail, encoding="utf-8")
